import type APIData from "~/types.d.ts";
export const mainGalleries: APIData.Postcard[] = [
  {
    title: "Women's Rights",
    image: "2KXJ8Z8KLJWR",
    imageTitle: "Bryan L. Bossier postcard collection, 1880s-1920s [000034_01]",
    width: "2801",
    height: "4169",
    link: "2KXJ8ZSA9MW04",
    context: "",
  },
  {
    title: "Reading and Writing",
    image: "2KXJ8ZS6CRVOA",
    imageTitle: "Le Koh-i-noor",
    width: "9504",
    height: "6336",
    link: "2KXJ8ZSAKD0AX",
    context: "",
  },
  {
    title: "Bicycling",
    image: "2KXJ8ZY0CNVG",
    imageTitle: "Sur la francaise-diamant",
    width: "2856",
    height: "4099",
    link: "2KXJ8ZSAKD58D",
    context: "",
  },
  {
    title: "Chicago",
    image: "2KXJ8ZFA30EC",
    imageTitle: "Most beautiful diner in Chicago",
    width: "3600",
    height: "2290",
    link: "2KXJ8ZSAKD6V9",
    context: "",
  },
  {
    title: "Stories: Oilettes",
    image: "2KXJ8ZI9QNAQ",
    imageTitle: "Evening on the beach",
    width: "3842",
    height: "2496",
    link: "2KXJ8ZSAKDAG7",
    context: "",
  },
  {
    title: "Alcohol",
    image: "2KXJ8ZS64AUMR",
    imageTitle: "Woman and cherub",
    width: "6336",
    height: "9504",
    link: "2KXJ8ZSAKDB98",
    context: "",
  },
  {
    title: "Dogs",
    image: "2KXJ8ZIV2E16",
    imageTitle: "Two Dobermans",
    width: "3893",
    height: "2561",
    link: "2KXJ8ZSAKDC09",
    context: "",
  },
  {
    title: "Cats",
    image: "2KXJ8ZIDXAZ4",
    imageTitle: "Family cares",
    width: "2527",
    height: "3899",
    link: "2KXJ8ZSAKDD11",
    context: "",
  },
  {
    title: "Thanksgiving",
    image: "2KXJ8ZF6ZX9J",
    imageTitle: "Thanks to him who spared our living...",
    width: "3600",
    height: "2355",
    link: "2KXJ8ZSAKDE3I",
    context: "",
  },
  {
    title: "Santa Claus",
    image: "2KXJ8Z8AVDUE",
    imageTitle: "Christmas greetings",
    width: "4103",
    height: "2718",
    link: "2KXJ8ZSAKDHEB",
    context: "",
  },
  {
    title: "Valentine's Day",
    image: "2KXJ8ZIDZ6WB",
    imageTitle: "A joyous Valentine Day",
    width: "2488",
    height: "3884",
    link: "2KXJ8ZSAKDJCR",
    context: "",
  },
  {
    title: "Easter",
    image: "2KXJ8ZIDY0UI",
    imageTitle: "A happy Easter",
    width: "3861",
    height: "2505",
    link: "2KXJ8ZSAKDKDK",
    context: "",
  },
  {
    title: "Back to School",
    image: "2KXJ8ZS6G18VE",
    imageTitle: "Stealing Apples",
    width: "9504",
    height: "6336",
    link: "2KXJ8ZSAKDMYB",
    context: "",
  },
  {
    title: "Newberry",
    image: "2KXJ8ZSVHH99C",
    imageTitle: "Chicago, Ill. Newberry Library",
    width: "3775",
    height: "2280",
    link: "2KXJ8ZSAKDPK2",
    context: "",
  },
  {
    title: "Christmas",
    image: "2KXJ8ZIH06FE",
    imageTitle: "A merry Christmas",
    width: "2540",
    height: "3900",
    link: "2KXJ8ZSAKDQ5P",
    context: "",
  },
  {
    title: "Coffee & Tea",
    image: "2KXJ8ZEV5X3L",
    imageTitle: "Mol's Coffee House, Exeter",
    width: "3862",
    height: "2495",
    link: "2KXJ8ZSAKDRBQ",
    context: "",
  },
  {
    title: "Halloween",
    image: "2KXJ8ZPZ1RNA",
    imageTitle: "May the Halloween fates spin you a lucky thread of life",
    width: "3600",
    height: "2344",
    link: "2KXJ8ZSAKDX4O",
    context: "",
  },
];
export default mainGalleries;
